### ISSUE TITLE
Nested validation with more than one object nested

### ISSUE THREAD

**Issue by jhoermann** [nijikokun/Validator#7]
This:

> var schema = {
>  backpack: {
>    type: Object,
>    required: true,
> 
>    team: {
>      type: Object,
>      required: true,
>      passwordTeam: {
>        type: "String"
>      }
>    },
> 
>    inventory: {
>      type: Array,
>      default: [],
>      length: {
>        max: 255
>      }
>    }
>  },
> 
>  name: {
>    type: "String",
>    required: true,
>    length: {
>      min: 3,
>      max: 36
>    },
>    test: /^[a-z0-9]+$/i
>  },
> 
>  password: {
>    type: "String"
>  }
> }

leads to an error:

> node_modules/schema-validator/validator.js:166
>        } else if (Object.prototype.toString.call(this.schema[key][field]) == 
>                                                                  ^
> TypeError: Cannot read property 'passwordteam' of undefined
>    at loop (node_modules/schema-validator/validator.js:166:67)
>    at loop (node_modules/schema-validator/validator.js:167:20)
>    at null.<anonymous> (cad-backend/node_modules/schema-validator/validator.js:178:17)
>    at Validator.loop (cad-backend/node_modules/schema-validator/validator.js:217:14)
>    at Validator.validate (cad-backend/node_modules/schema-validator/validator.js:176:12)
>    at Validator.check (cad-backend/node_modules/schema-validator/validator.js:91:15)
>    at Object.<anonymous> (cad-backend/node_modules/schema-validator/test.js:89:18)
>    at Module._compile (module.js:460:26)
>    at Object.Module._extensions..js (module.js:478:10)
>    at Module.load (module.js:355:32)
> Is it possible to add multiple nested designs?

**Comment by tomvlk** [comment]
I have exactly the same problem. Is there going to be a fix for this soon?

**Comment by andrew-aladev** [comment]
Problem is [here](https://github.com/nijikokun/Validator/blob/master/validator.js#L163)

How it is possible to write a recursion and try to access variable by using `this.schema[key][field]`? I couldn't understand it. This code doesn't look like fixable. We have to use another validator.
